### ISSUE TITLE
Redot Logo needs to be desaturated for darker backgrounds

### ISSUE THREAD

**Issue by tokengamedev** [Redot-Engine/redot-proposals#23]
### Tested versions

4.4

### System information

Windows 11

### Issue description

In case of darker backgrounds like in task bar or other places it looks odd and hurts the eye, but in white background it looks ok 
e.g., in windows startup compared to other red logos
![image](https://github.com/user-attachments/assets/5da0b04f-fe99-47fa-ab3a-b1494f118315)

the way to handle this without impacting hue is by reducing the saturation of colors.
currently the saturation is at 100%, it can be reduced by ~20%

The example given below is for comparison of various saturation values
![icons](https://github.com/user-attachments/assets/ee1c75d6-335f-4620-92c6-8e21d12fcd33)

If any other technique known, it can be applied too.

### Steps to reproduce

icons in editor

### Minimal reproduction project (MRP)

N.A

**Comment by joey-wheeler99** [comment]
The logo has outlined version to tackle the contrast issue. 
![image](https://github.com/user-attachments/assets/2ea66d30-794f-4411-9659-97ad7a61d79d)
