### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by Hexagrim** [Redot-Engine/redot-proposals#37]
### Describe the project you are working on

Im making a 3d game

### Describe the problem or limitation you are having in your project

The godot engine is laggy, even in an empty scene

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Optimizations to the editor and the renderer

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

uhh idk 👍

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Its will be very helpful breh

### Is there a reason why this should be core and not an add-on in the asset library?

cuz why tf would you add it there

**Comment by Spartan322** [comment]
Please don't make proposals like this, this is not a feature nor a proposal.
