### ISSUE TITLE
OpenGl And Driver Support

### ISSUE THREAD

**Issue by Hexagrim** [Redot-Engine/redot-proposals#38]
### Describe the project you are working on

A 3D First Person Horror game.

### Describe the problem or limitation you are having in your project

My Pc and probably many others, have old or limited hardware which are mid in performance but lack due to the advanced vulkan renderer in godot which leads to Fps degrade, I got 30 fps on an empty scene in a laptop where I get 60+fps While running Games like Minecraft on high settings.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding a better support for open gl could help. Altough there is support for open gl right now, It lacks alot of performance optimizations and rendering features. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

My proposal works by making use of open gl renderer and other various optimizations and graphics features. Altough I am not able to provide a detailed way of making this nor do i have any idea about it, its just a proposal :)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes

### Is there a reason why this should be core and not an add-on in the asset library?

It is a good argument, but I dont think having better functionality should be in the asset library, It should be something the engine should come out of the box.

(extra){I made this post because I want to use redot for my game seeing how it is community driven and similar to godot. Even if this proposal feels unnecessary, at least optimizing the engine would be a enhancement as a lightweight game engine, the games made in it are expected to work in lower hardware.}

**Comment by Spartan322** [comment]
This isn't a proposal, proposals should submit some kind of plan, please don't ask to generically fix performance, that's not the point of the issue tracker, if we knew of ways to do so we would.
