### ISSUE TITLE
Android mobile editor 

### ISSUE THREAD

**Issue by RichardMiller90** [Redot-Engine/redot-proposals#46]
### Describe the project you are working on

Why isn't there an android editor available. Godot editor ran run on mobile but I can't find redot engine mobile editor, Why? Aren't your guy based on the godot.

### Describe the problem or limitation you are having in your project

![Uploading Screenshot_20241022-175038.jpg…]()

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It shouldn't be any trouble making a mobile editor since redot is not an original project but a rippoff 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![Uploading Screenshot_20241022-175154.jpg…]()

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't see why redot can't do the same.

### Is there a reason why this should be core and not an add-on in the asset library?

The godot mobile editor has helped ppl who can't afford a pc to create ir carry on with their project.

**Comment by ExtraBytez** [comment]
https://github.com/Redot-Engine/redot-engine/releases
did you look?
