### ISSUE TITLE
Support for editing @export values of tilemap squares

### ISSUE THREAD

**Issue by ExtraBytez** [Redot-Engine/redot-proposals#66]
### Describe the project you are working on

Zelda 1 clone

### Describe the problem or limitation you are having in your project

Would like to be able to change each tilemap sqaures values

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

make it alot more organized then making a ton of nodes in the scene tree

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

right clicking while in tile map editor mode brings up a menu of all the export nodes of the tilemap thing

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no i dont think so at least

### Is there a reason why this should be core and not an add-on in the asset library?

i dont think this can be done with addons correct me if im wrong
1 more thing i would like to add this was proposed in godots repo but never done 
https://github.com/godotengine/godot-proposals/issues/7249

**Comment by Spartan322** [comment]
This is not a valid way to fill out a proposal.
